name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Usa Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Instala dependências do frontend
      - name: Instala dependências do Angular
        working-directory: .
        run: npm install

      # Builda o frontend
      - name: Build do Angular
        run: npm run build -- --configuration=production

      # Roda testes do frontend (sem Karma)
      - name: Testes do Angular
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # Instala dependências do backend
      - name: Instala dependências do Node.js backend
        working-directory: ./server
        run: npm install

      # (Opcional) Start backend e testa endpoints com curl ou test framework

      # Sucesso!
      - name: Concluído com sucesso
        run: echo "✅ Build e testes executados com sucesso!"
